### PR TITLE
Fix compilation for Linux v5.8

### PR DESCRIPTION
**Pull request by MaxG87**
Several changes were cherry-picked to fix the compilation for Linux v5.8. Unfortunately, another warning had to be suppressed too.

### CODE REVIEW

**Comment by MaxG87** [comment]
Works on Debian Testing with kernel 5.8.0-1. Device is DWA-182_Rev_D1.

**Comment by seif** [comment]
Works on ubuntu 20.10 with kernel 5.8.0-28-generic

**Comment by MaxG87** [comment]
This version of the driver also works on Debian Testing with kernel 5.9.

**Comment by molpopgen** [comment]
Confirm working on Ubuntu 20.10 with 5.8.0-7630-generic.  Device is a BrosTrend AC1

**Pull request merged**
