### PR TITLE
Add LED control

### PR DESCRIPTION
**Pull request by vvv-ca**

### CODE REVIEW

**Comment by vvv-ca** [comment]
Looks like the builds are failing because of incorrect gcc version.

**Comment by MaxG87** [comment]
Hi! Sorry for not responding so long. Could you please elaborate what exactly is added by this PR? My stick has a blinking LED, so I wonder what would be added.

I am also interested where your changes come from. Where they copied from a different driver? Did you write them on your own?

**Comment by vvv-ca** [comment]
Hello, 
the PR adds the module parameter that allows users to control the LED behavior. So you can turn the LED completely off (which is what I use it for), always on, or the standard blinking behavior.
I mostly copied the code from previous versions of the driver.

**Comment by MaxG87** [comment]
Could you please rebase the PR against the recent 5.8.71... ? Furthermore, your changes introduce a compiler warning. I'd prefer if a better way could be found. Maybe it is enough to change the declaration?

```
.../rtl88x2bu/hal/led/hal_led.c: In function ‘rtw_led_set_strategy’:
.../hal/led/hal_led.c:66:38: warning: implicit conversion from ‘enum _LED_STATE’ to ‘LED_CTL_MODE’ {aka ‘enum _LED_CTL_MODE’} [-Wenum-conversion]
   66 |         rtw_led_control(pri_adapter, RTW_LED_OFF);
      |                                      ^~~~~~~~~~~
  CC [M]  .../rtl88x2bu/hal/led/hal_usb_led.o
```

**Pull request closed without merging**
