### PR TITLE
feat: add debian packaging support

### PR DESCRIPTION
**Pull request by NachoLulu**
add debian dkms packaging support

### CODE REVIEW

**Comment by MaxG87** [comment]
Thank you very much for your contribution.

I could not figure out what the goal of this PR is. Will it prepare the repository such that one will be able to build  Debian packages to install, rather than using the `deploy.sh`? Or do you intend to contribute the package to Debian unstable? Could you add some documentation explaining this to README.md?

I noticed that you included some files which mention that you should include some content or delete them. Could you please do so?

Last but maybe most important: I am suspect that Debian packaging might be too much of complexity for the project at the moment.
@cilynx : What do you think?

**Comment by NachoLulu** [comment]
Thank you for your reply

I mentioned that the main purpose of this PR is to provide convenience for some Debian users who need this driver package to solve some network card adaptation problems. 

We all know that Debian has a set of package management mechanism, so the main purpose of adding the debian directory is to compile the source code into a deb package, so that the debian user will use the native kernel version to compile the driver module when installing.

**Comment by Nacho-meteor** [comment]
> 非常感谢您的贡献。
> 
> 我不知道这个PR的目标是什么。它会准备存储库，以便能够构建Debian软件包来安装而不是使用`deploy.sh`吗？还是您打算将软件包提供给Debian不稳定版？您可以在README.md中添加一些说明此内容的文档吗？
> 
> 我注意到您包含了一些文件，其中提到您应该包含一些内容或将其删除。你能这样做吗？
> 
> 最后但也许是最重要的一点：我怀疑Debian打包对于目前的项目而言可能过于复杂。
> @cilynx：您怎么看？

**Comment by NachoLulu** [comment]
> 谢谢您的回复
> 
> 我提到过，此PR的主要目的是为需要此驱动程序包来解决某些网卡适配问题的某些Debian用户提供便利。
> 
> 众所周知，Debian具有一套软件包管理机制，因此添加debian目录的主要目的是将源代码编译为一个deb软件包，以便debian用户将在以下情况下使用本机内核版本来编译驱动程序模块：安装。

@MaxG87

**Comment by MaxG87** [comment]
>> 谢谢您的回复
>>
>> 我提到过，此PR的主要目的是为需要此驱动程序包来解决某些网卡适配问题的某些Debian用户提供便利。
>>
>> 众所周知，Debian具有一套软件包管理机制，因此添加debian目录的主要目的是将源代码编译为一个deb软件包，以便debian用户将在以下情况下使用本机内核版本来编译驱动程序模块：安装。
I am very sorry but I only see Asian characters. Could you please translate
that?

As of your argument for ease of install: I do not see the benefit a Debian
packaging support would give over the `deploy.sh` script. That said script
works quite reliably for me and, thanks to `dkms`, provides the driver to new
kernel versions. How would your PR improve this?

**Comment by NachoLulu** [comment]
> > 谢谢您的回复 > > 我提到过，此PR的主要目的是为需要此驱动程序包来解决某些网卡适配问题的某些Debian用户提供便利。 > > 众所周知，Debian具有一套软件包管理机制，因此添加debian目录的主要目的是将源代码编译为一个deb软件包，以便debian用户将在以下情况下使用本机内核版本来编译驱动程序模块：安装。
> I am very sorry but I only see Asian characters. Could you please translate that? As of your argument for ease of install: I do not see the benefit a Debian packaging support would give over the `deploy.sh` script. That said script works quite reliably for me and, thanks to `dkms`, provides the driver to new kernel versions. How would your PR improve this?

Thank you for your reply

I mentioned that the main purpose of this PR is to provide convenience for some Debian users who need this driver package to solve some network card adaptation problems.

We all know that Debian has a set of package management mechanism, so the main purpose of adding the debian directory is to compile the source code into a deb package, so that the debian user will use the native kernel version to compile the driver module when installing.

**Pull request closed without merging**
