### PR TITLE
Linux 5.8 compatibility

### PR DESCRIPTION
**Pull request by mabrand**
These work for me, but should be evaluated by someone with actual expertise.

### CODE REVIEW

**Comment by MaxG87** [comment]
Maybe one could find a nonconflicting name too? If the struct can be moved to the C file the renaming should be manageable, shouldn't it?

**Comment by mabrand** [comment]
My thinking was that changing the name of the struct would come at the cost of extra divergence from the original code and from other descendants of the original, making it harder to borrow patches between rtl88x versions, harder to merge with newer upstream sources, harder to search the web for related error messages, etc. 

This is only a weak preference, so feel free to rename. And, if other influential related projects are solving this problem by renaming the struct, it might be best to follow them.

**Comment by MaxG87** [comment]
You are entirely right. I did not think of your arguments. My entire concern were problems due to name clashes. Propper diffs are by far more important in this projects.

**Comment by Medullitus** [comment]
On which ubuntu or mint relaseas the driver works ??

**Comment by mabrand** [comment]
For example, https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.8-rc5/amd64/

**Review by SuzukiHonoka — APPROVED** [review]
awesome work!

**Review by kurtie — APPROVED** [review]

**Comment by silvernode** [comment]
I can confirm, patching my git repo with this patch fixed the problem and with no unexpected side effects/errors. You are a life saver, I was panicking when the build kept failing and I needed to get some work done. Thanks.

**Comment by StaticallyTypedRice** [comment]
Works on Fedora 32 with kernel `5.8.4-200.fc32.x86_64`!

**Comment by MaxG87** [comment]
Works on Ubuntu 20.04 with kernel 5.8.0. Device is DWA-182_Rev_D1.

**Comment by MaxG87** [comment]
Works on Debian Testing with kernel 5.8.0-1. Device is DWA-182_Rev_D1.

This is very significant because since quite some time I got reproducible kernel freezes with this driver on recent kernels. Thus, having this merged would fix this situation for me and hopefully others too.

**Comment by elobuho** [comment]
Works on 5.8.11-1-MANJARO

@mabrand 
Thanks for this update.

**Comment by fpratbae** [comment]
Works on 5.8.0-0.bpo.2-amd64 in Debian 10
Thanks

**Comment by mfcochauxlaberge** [comment]
I just updated to Ubuntu 20.10 and this driver stopped working. I tried this PR (removed the moduled and rebuilt it) and everything works fine now. Thanks a lot.

**Comment by kaaloo** [comment]
Same here!  This probably needs to be merged into a 5.8 branch though.

**Pull request merged**
